[package]
name = "neoqmllsp"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "The Lsp for cmake"
homepage = "https://github.com/Decodetalkers/neocmakelsp"
authors = ["Decodertalkers <aakari@tutanota.com>"]
keywords = ["lsp"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-lsp = "0.17.0"
lsp-types = "0.93.0"
tokio = { version = "1.18.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing-subscriber = "0.3.11"
tree-sitter = "0.20.7"
tree-sitter-qmljs = "0.1.1"
regex = "1"
once_cell = "1.12.1"
anyhow = "1.0.58"
